connote-service:
  build: ./connote-service
  ports:
    - "8081:8080"
  links:
    - etcd

customer-service:
  build: ./customer-service
  ports:
    - "8082:8080"
  links:
    - etcd

transport-service:
  build: ./transport-service
  ports:
    - "8083:8080"
  links:
    - customer-service
    - connote-service
    - etcd

etcd:
  image: quay.io/coreos/etcd:v2.2.5
  command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
  ports:
    - "2379:2379"
